import { chromium } from "playwright-core";

const baseUrl = (process.env.RTS_BASE_URL || "http://127.0.0.1:4318").replace(/\/$/, "");
const browser = await chromium.launch({ headless: true, executablePath: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.setDefaultTimeout(10000);
page.setDefaultNavigationTimeout(10000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
await page.goto(baseUrl, { waitUntil: "networkidle" });
await page.locator("#new-tree-btn").click();
if (!await page.locator("#tree-dialog").evaluate(el => el.open)) throw new Error("新建树对话框未打开");
await page.locator('[data-mode="ai"]').click();
if (await page.locator("#search-mode button").count() !== 2) throw new Error("AI 检索缺少两种检索模式");
await page.locator('[data-search-mode="readable"]').click();
if (!await page.locator('[data-search-mode="readable"]').evaluate(element => element.classList.contains("active"))) throw new Error("可阅读全文优先模式未生效");
if (await page.locator("#research-progress").isVisible()) throw new Error("AI 检索尚未开始时进度条错误显示");
await page.locator("#form-tree-name").fill("测试研究方向");
await page.locator("#save-tree-btn").click();
if (!await page.locator("#research-message").isVisible()) throw new Error("缺少 API Key 时没有在弹窗内显示错误");
await page.evaluate(() => sessionStorage.setItem("deepseek-key", "test-key"));
await page.route("**/api/deepseek/research/stream", async route => {
  await new Promise(resolve => setTimeout(resolve, 350));
  await route.fulfill({ status: 200, contentType: "text/event-stream", body: `event: progress\ndata: {"percent":38,"stage":"正在检索公开论文库","detail":"已完成 2/4 路检索"}\n\nevent: error\ndata: {"error":"模拟检索失败"}\n\n` });
});
await page.locator("#save-tree-btn").click();
if (!await page.locator("#research-progress").isVisible()) throw new Error("AI 检索开始后进度条没有显示");
await page.locator("#research-message").filter({ hasText: "模拟检索失败" }).waitFor();
if (await page.locator("#research-progress-percent").textContent() !== "38%") throw new Error("进度条没有接收服务端实际阶段进度");
if (await page.locator("#research-progress").isVisible()) throw new Error("AI 检索失败后进度条没有停止");
await page.locator('[data-close="tree-dialog"]').last().click();
if (await page.locator("#tree-dialog").evaluate(el => el.open)) throw new Error("空标题时无法取消新建树");
await page.locator("[data-open-tree]").first().click();
if (await page.locator(".access-marker").count() !== await page.locator(".paper-node").count()) throw new Error("论文访问状态标记数量不完整");
if (await page.locator(".relation-label").count() !== await page.locator(".relation").count()) throw new Error("论文关系线缺少中文关系标签");
const relationKinds = new Set(await page.locator(".relation-label text").allTextContents());
if (relationKinds.size < 5) throw new Error(`内置研究树关系类型仍过于单一：${[...relationKinds].join("、")}`);
if (await page.locator("#relationship-overview details").count() !== 6) throw new Error("研究脉络总览缺少五条分支或跨分支区域");
if (await page.locator("#relationship-overview details[open]").count()) throw new Error("研究脉络总览没有默认折叠");
await page.locator('.paper-node[data-paper="system-2"]').hover();
const tooltipText = await page.locator("#paper-tooltip").innerText();
if (!tooltipText.includes("全文状态") || !tooltipText.includes("分析依据") || !tooltipText.includes("置信度")) throw new Error("悬停说明缺少访问状态或分析依据");
const relationshipText = await page.locator("#relationship-panel").innerText();
if (!relationshipText.includes("前序来源") || !relationshipText.includes("分页式注意力") || !relationshipText.includes("闪存注意力")) throw new Error("关系速览没有同时显示直接前序关系");
if (await page.locator(".relation.trace-active").count() !== 2) throw new Error("论文悬停没有只高亮直接前后关系");
if (!await page.locator("#tree-canvas svg.trace-mode").isVisible()) throw new Error("论文悬停时没有进入回溯线高亮模式");
if (!await page.locator(".branch-paths.trace-active .root-branch").isVisible()) throw new Error("论文悬停时没有高亮主干到分支的回溯线");
if (!await page.locator(".branch-twig.trace-paper").count()) throw new Error("论文悬停时没有高亮论文树枝");
await page.mouse.move(2, 2);
await page.waitForTimeout(80);
if (await page.locator("#paper-tooltip").isVisible()) throw new Error("光标离开论文框后悬停注释没有消失");
if (await page.locator("#tree-canvas svg.trace-mode").count()) throw new Error("未点击论文时，光标离开后仍保留临时高亮");
if (!(await page.locator("#relationship-panel").innerText()).includes("选择论文")) throw new Error("未点击论文时，光标离开后关系栏没有恢复空状态");
await page.locator('.paper-node[data-paper="system-2"]').click();
await page.waitForTimeout(320);
if (!await page.locator('.paper-node[data-paper="system-2"].locked').count()) throw new Error("单击论文后没有进入锁定状态");
if (!await page.locator("#pin-relationship-btn").evaluate(element => element.classList.contains("active"))) throw new Error("单击论文后关系栏没有显示已固定");
await page.locator('.paper-node[data-paper="system-3"]').click();
await page.waitForTimeout(320);
if (await page.locator(".paper-node.locked").count() !== 2) throw new Error("单击另一篇论文时覆盖了前一篇锁定");
if (!await page.locator('.paper-node[data-paper="system-2"].locked').count() || !await page.locator('.paper-node[data-paper="system-3"].locked').count()) throw new Error("多篇论文没有保持独立锁定状态");
if (await page.locator("#relationship-panel .relationship-paper-block").count() !== 2) throw new Error("右侧关系栏没有同时展示两篇锁定论文");
const multiRelationshipText = await page.locator("#relationship-panel").innerText();
if (!multiRelationshipText.includes("高效可定制注意力推理引擎") || !multiRelationshipText.includes("精确的 8 位注意力")) throw new Error("多选关系栏缺少锁定论文的分组说明");
await page.mouse.move(2, 2);
await page.waitForTimeout(280);
if (await page.locator(".relation.trace-active").count() !== 3) throw new Error("多篇锁定论文的关系线没有合并高亮");
await page.locator('.paper-node[data-paper="system-2"]').click();
await page.waitForTimeout(320);
if (await page.locator(".paper-node.locked").count() !== 1 || !await page.locator('.paper-node[data-paper="system-3"].locked').count()) throw new Error("再次单击没有只解除当前论文的锁定");
if (await page.locator(".relation.trace-active").count() !== 1) throw new Error("解除一篇后高亮没有保留其他锁定论文");
await page.locator('.paper-node[data-paper="system-3"]').click();
await page.waitForTimeout(320);
if (await page.locator(".paper-node.locked").count()) throw new Error("再次单击最后一篇论文后没有解除锁定");
if (await page.locator("#tree-canvas svg.trace-mode").count()) throw new Error("解除最后一篇论文后没有清除关系高亮");
if (!(await page.locator("#relationship-panel").innerText()).includes("选择论文")) throw new Error("解除最后一篇论文后关系栏没有恢复空状态");
await page.mouse.move(2, 2);
await page.locator('.paper-node[data-paper="system-2"]').hover();
await page.mouse.move(2, 2);
await page.waitForTimeout(50);
if (await page.locator("#paper-tooltip").isVisible()) throw new Error("鼠标离开论文节点后注释框没有消失");
if (await page.locator(".relation.trace-active").count()) throw new Error("未固定时移开论文后仍保留临时关系高亮");
if (!(await page.locator("#relationship-panel").innerText()).includes("选择论文")) throw new Error("移开论文后右侧临时关系说明没有清除");
await page.locator('.paper-node[data-paper="system-3"]').hover();
if (!(await page.locator("#relationship-panel").innerText()).includes("精确的 8 位注意力")) throw new Error("悬停另一篇论文时关系说明没有切换");
await page.mouse.move(2, 2);
await page.waitForTimeout(50);
if (await page.locator("#tree-canvas svg.trace-mode").count()) throw new Error("第二次悬停离开后回溯线仍处于高亮模式");
if (await page.locator(".trace-active,.trace-paper,.trace-target,.trace-ancestor").count()) throw new Error("第二次悬停离开后仍残留高亮标记");
if (!(await page.locator("#relationship-panel").innerText()).includes("选择论文")) throw new Error("第二次悬停离开后关系栏没有恢复空状态");
await page.route("**/api/deepseek/relation/stream", async route => {
  await new Promise(resolve => setTimeout(resolve, 180));
  await route.fulfill({ status: 200, contentType: "text/event-stream", body: `event: progress\ndata: {"percent":64,"stage":"分析论文联系","detail":"正在生成中文说明"}\n\nevent: result\ndata: {"data":{"type":"improves","explanation":"模拟更新关系：后续论文在前序工作的基础上改进了推理效率。","confidence":0.72,"analysisBasis":"abstract"}}\n\n` });
});
await page.locator('.paper-node[data-paper="system-2"]').click();
await page.waitForTimeout(320);
await page.locator("#relationship-panel .relationship-menu summary").first().click();
await page.locator("#relationship-panel [data-reanalyze-relationship]").first().click();
await page.locator("#relationship-panel .relationship-progress").waitFor();
await page.locator("#relationship-panel").filter({ hasText: "模拟更新关系" }).waitFor();
if (await page.locator("#relationship-panel .relationship-kind").first().innerText() !== "改进") throw new Error("AI 单关系重判没有更新关系类型");
await page.locator("#undo-btn").click();
await page.locator("#relationship-panel").filter({ hasText: "模拟更新关系" }).waitFor({ state: "hidden" });
if ((await page.locator("#relationship-panel").innerText()).includes("模拟更新关系")) throw new Error("AI 关系更新无法撤销");
await page.unroute("**/api/deepseek/relation/stream");
await Promise.all([page.waitForURL(/\/reader\.html\?/), page.locator(".branch-node").first().click()]);
if (!page.url().includes("/reader.html")) throw new Error("点击树内分支框没有直接跳转到奠基论文");
if (!await page.locator("#back-link").isVisible()) throw new Error("单篇阅读页缺少返回研究树入口");
await page.goBack({ waitUntil: "domcontentloaded" });
await page.locator(".branch-node").first().waitFor();
await page.locator('[data-side-tab="branches"]').click();
const branchReaderPromise = page.context().waitForEvent("page", { timeout: 10000 });
await page.locator("[data-view-branch]").first().click();
const branchReader = await branchReaderPromise;
await branchReader.waitForLoadState("domcontentloaded");
if (!page.url().includes("#tree=")) throw new Error("从侧栏打开分支阅读目录时覆盖了原研究树页面");
if (!branchReader.url().includes("/branch-reader.html")) throw new Error("点击研究分支后没有打开分支阅读目录");
if (!await branchReader.locator("#papers").isVisible()) throw new Error("分支阅读目录没有显示论文列表");
const nestedReaderPromise = page.context().waitForEvent("page", { timeout: 10000 });
await branchReader.locator(".paper").first().click();
const nestedReader = await nestedReaderPromise;
await nestedReader.waitForLoadState("domcontentloaded");
if (!nestedReader.url().includes("/reader.html")) throw new Error("分支目录中的论文没有打开单篇阅读页");
await nestedReader.close();
await branchReader.close();
const treeUrlBeforeDoubleClick = page.url();
const directReaderPromise = page.context().waitForEvent("page", { timeout: 10000 });
await page.locator(".paper-node").first().dblclick();
const directReader = await directReaderPromise;
await directReader.waitForLoadState("domcontentloaded");
if (!directReader.url().includes("/reader.html")) throw new Error("双击论文没有打开论文阅读页");
if (page.url() !== treeUrlBeforeDoubleClick) throw new Error("双击论文时覆盖了原研究树页面");
if (!await directReader.locator("#choose-btn").isVisible()) throw new Error("本地论文替换入口未显示");
await directReader.close();
await page.locator(".paper-node").first().click();
await page.waitForTimeout(320);
await page.locator("[data-edit-paper]").waitFor();
await page.locator("[data-edit-paper]").click();
if (!await page.locator("#paper-dialog").evaluate(el => el.open)) throw new Error("论文编辑对话框未打开");
await page.locator('[data-close="paper-dialog"]').last().click();
await page.locator('[data-side-tab="queue"]').click();
await page.locator("#pdf-input").setInputFiles({ name: "smoke-test.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4\n%%EOF") });
await page.locator("[data-remove-task]").click();
await page.locator(".queue-item").waitFor({ state: "detached" });
await page.locator("#export-btn").click();
if (!await page.locator("#export-dialog").evaluate(el => el.open)) throw new Error("研究树导出对话框未打开");
const mobilePage = await browser.newPage({ viewport: { width: 390, height: 844 } });
await mobilePage.goto(`${baseUrl}/#tree=efficient-attention`, { waitUntil: "networkidle" });
await mobilePage.locator('.relation-peek-control[data-paper="system-2"]').click();
if (!await mobilePage.locator("#relationship-panel.mobile-open").isVisible()) throw new Error("手机端论文关系入口没有打开底部抽屉");
if (!mobilePage.url().includes("#tree=efficient-attention")) throw new Error("手机端查看关系时错误跳转到了论文阅读页");
await mobilePage.locator("#toggle-relationship-btn").click();
if (await mobilePage.locator("#relationship-panel.mobile-open").isVisible()) throw new Error("手机端关系抽屉无法关闭");
await mobilePage.close();
await page.goto(`${baseUrl}/reader.html?paper=fixture-lock&title=Paid%20Paper&titleZh=%E4%BB%98%E8%B4%B9%E8%AE%BA%E6%96%87&status=institutional_required&basis=metadata&source=https%3A%2F%2Fdoi.org%2F10.0000%2Ffixture`, { waitUntil: "domcontentloaded" });
if (!await page.locator(".fallback.locked").isVisible()) throw new Error("机构权限论文未显示专用阅读状态");
if (!await page.locator(".fallback").innerText().then(text => text.includes("不会要求或保存学校账号、密码和 Cookie"))) throw new Error("机构权限页面缺少隐私说明");
if (await page.locator("iframe").count()) throw new Error("机构权限论文被错误显示为可阅读 PDF");
if (errors.length) throw new Error(errors.join("\n"));
console.log("UI smoke test passed");
await browser.close();
